# Use docs.noctalia.dev for guides

[shell]
font_family = "Space Mono"

[shell.launcher]
sort_by_usage = true

[shell.screenshot]
directory = "~/Media/Pictures/Screenshots"

[theme]
mode = "dark"

[bar.default]
position = "top"
layer = "top"
thickness = 38
border_width = 3.0
scale = 1.2
margin_ends = 10

widget_spacing = 8
# font_family = "Space Mono"

# default start  = ["launcher", "wallpaper", "workspaces"]
start = ["workspaces", "spacer", "media"]

# default center = ["clock"]
center = ["clock"]

# default end    = ["media", "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "control-center", "session"]
end = ["notifications", "spacer", "network", "volume", "bluetooth", "battery", "tray", "session"]

[widget.network]
show_label = false

[wallpaper]
enabled = true

[backdrop]
enabled = true
blur_intensity = 0.5
tint_intensity = 0.3
